import io.floodplain.build.FloodplainDeps

dependencies {
    implementation(project(":immutable-api"))
    implementation(project(":immutable-impl"))
    implementation(project(":replication-api"))
    implementation(project(":replication-impl"))
    implementation(project(":replication-json"))
    implementation(project(":replication-protobuf"))
    implementation(project(":streams"))
    implementation(project(":streams-api"))
    implementation(project(":floodplain-stream-topology"))
    implementation(project(":floodplain-debezium"))
    implementation(project(":floodplain-direct"))
    implementation(project(":floodplain-api"))
    compile(FloodplainDeps.slf4j)
    compile(FloodplainDeps.kotlinLogging)
    implementation(FloodplainDeps.debeziumPostgres)
    implementation(FloodplainDeps.debeziumMySQL)
    implementation(FloodplainDeps.debeziumEmbedded)
    implementation(FloodplainDeps.argParser)
    testCompile(FloodplainDeps.jUnit)
    testCompile(FloodplainDeps.testContainer)
    implementation(FloodplainDeps.kafkaConnectRuntime)
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation(FloodplainDeps.kotlinCoroutines)
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}
