exceptions:
  SwallowedException:
    active: false

#    excludes: ['**/Chunk.kt']
formatting:
  MaximumLineLength:
    maxLineLength: 140

complexity:
  TooManyFunctions:
    excludes: [ '**/IMessage.kt','**/test/**' ]
  LongMethod:
    excludes: ['**/test/**']
  LargeClass:
    excludes: ['**/test/**']

style:
  ReturnCount:
    active: true
    max: 2

build:
  maxIssues: 200 # break the build if more than ten weighted issues are found
  weights:
    complexity: 2 # every rule of the complexity rule set should count as if two issues were found...
    LongParameterList: 1 # ...with the exception of the LongParameterList rule.
  excludeCorrectable: true

