exceptions:
  SwallowedException:
    excludes: ['io/floodplain/external/**']

formatting:
  MaximumLineLength:
    maxLineLength: 120

complexity:
  TooManyFunctions:
    excludes: [ '**/IMessage.kt','**/test/**' ]
  LongMethod:
    excludes: ['**/test/**']
  LargeClass:
    excludes: ['**/test/**']
  LongParameterList:
    functionThreshold: 7
    constructorThreshold: 10
    ignoreDefaultParameters: true

style:
  ReturnCount:
    active: true
    max: 2

build:
  maxIssues: 145 # break the build if more than ten weighted issues are found
  weights:
    complexity: 2 # every rule of the complexity rule set should count as if two issues were found...
    LongParameterList: 1 # ...with the exception of the LongParameterList rule.
  excludeCorrectable: true

