import io.floodplain.build.FloodplainDeps

dependencies {
    api(FloodplainDeps.slf4j)
    compile(FloodplainDeps.kotlinLogging)
    implementation(project(":floodplain-stream-topology"))
    implementation(project(":immutable-api"))
    implementation(project(":streams-api"))
    implementation(project(":streams"))
    implementation(project(":floodplain-stream-topology"))
    implementation(project(":floodplain-dsl"))
    implementation(project(":floodplain-mongodb"))
    implementation(project(":floodplain-jdbc"))
    implementation(project(":floodplain-elasticsearch"))
    implementation(project(":floodplain-googlesheets"))
    implementation("io.confluent:kafka-connect-elasticsearch:5.5.0")
    implementation(FloodplainDeps.kotlinCoroutines)
    implementation(FloodplainDeps.jacksonDatabind310)
    testImplementation(project(":floodplain-test"))
    testImplementation(FloodplainDeps.jacksonCore)
    testImplementation(FloodplainDeps.jacksonDatabind)
    testImplementation(FloodplainDeps.testContainer)
    testImplementation(FloodplainDeps.testContainerKafka)
    testImplementation(FloodplainDeps.debeziumTestContainers)
    testImplementation(FloodplainDeps.mongoClientSync)
    testImplementation("org.junit.jupiter:junit-jupiter:${FloodplainDeps.junit_5_version}")
}
