/* Generated By:JJTree&JavaCC: Do not edit this line. ASTMappableNode.java */

package com.dexels.navajo.parser.compiled;


import com.dexels.immutable.api.ImmutableMessage;
import com.dexels.immutable.api.ImmutableMessage.ValueType;
import com.dexels.navajo.document.operand.Operand;
import com.dexels.navajo.expression.api.ContextExpression;
import com.dexels.navajo.expression.api.FunctionClassification;
import com.dexels.navajo.expression.api.TMLExpressionException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.function.Function;

@SuppressWarnings({"unchecked","rawtypes"})
final class ASTMappableNode extends SimpleNode {

	
	private static final Logger logger = LoggerFactory
			.getLogger(ASTMappableNode.class);
    String val = "";
    int args = 0;

    ASTMappableNode(int id) {
        super(id);
    }

	@Override
	public ContextExpression interpretToLambda(List<String> problems, String expression, Function<String, FunctionClassification> functionClassifier, Function<String,Optional<Node>> mapResolver) {
		Optional<Node> resolved = mapResolver.apply(val);
		if(resolved.isPresent()) {
			return resolved.get().interpretToLambda(problems, expression, functionClassifier, mapResolver);
		}
		return new ContextExpression() {
			
			@Override
			public boolean isLiteral() {
				return false;
			}
			
			@Override
			public Operand apply(Optional<ImmutableMessage> immutableMessage, Optional<ImmutableMessage> paramMessage) {
				if(true) {
					throw new RuntimeException("Not implemented on this");
				}
//		        if (mapNode == null) {
//		            throw new TMLExpressionException("No known mapobject resolver");
//		        }

		        List objects = null;

		        // Parameter array may contain parameters that are used when calling the get method.
		        Object[] parameterArray = null;

		        if (args > 0) {
		            objects = new ArrayList();
		        }
		        for (int i = 0; i < args; i++) {
		        		List<String> problems = new ArrayList<>();
		            Operand a = jjtGetChild(i).interpretToLambda(problems, expression,functionClassifier,mapResolver).apply(immutableMessage,paramMessage);
		            if(!problems.isEmpty()) {
		            		throw new TMLExpressionException(problems,expression);
		            }
		            if(objects!=null) {
		                objects.add(a.value);
		            }
		        }
		        if (objects != null) {
		            parameterArray = new Object[objects.size()];
		            parameterArray = objects.toArray(parameterArray);
		        }

		        try {
		        	// TODO remove totally?
		        	Object oValue = null;

		            if (oValue == null)
		                return Operand.NULL;
		            else if (oValue instanceof Float) {
		              return Operand.ofFloat(((Float) oValue).doubleValue()); 
		            } else if (oValue instanceof Long) {
			              return Operand.ofLong(((Long) oValue).longValue());
		            } else {
			              return Operand.ofDynamic(oValue);
		            }
		        } catch (Exception me) {
		            throw new TMLExpressionException(me.getMessage(),me);
		        }
			}


			@Override
			public Optional<ValueType> returnType() {
				return Optional.empty();
			}
			
			@Override
			public String expression() {
				return expression;
			}
		};
	}
}

