/* Generated By:JJTree&JavaCC: Do not edit this line. ASTOrNode.java */
package com.dexels.navajo.parser.compiled;

import com.dexels.immutable.api.ImmutableMessage;
import com.dexels.immutable.api.ImmutableMessage.ValueType;
import com.dexels.immutable.api.ImmutableTypeParser;
import com.dexels.navajo.document.operand.Operand;
import com.dexels.navajo.document.Property;
import com.dexels.navajo.expression.api.ContextExpression;
import com.dexels.navajo.expression.api.FunctionClassification;

import java.util.List;
import java.util.Optional;
import java.util.function.Function;

final class ASTOrNode extends SimpleNode {
    ASTOrNode(int id) {
        super(id);
    }
	@Override
	public ContextExpression interpretToLambda(List<String> problems, String expression, Function<String, FunctionClassification> functionClassifier, Function<String,Optional<Node>> mapResolver) {
		ContextExpression expA = jjtGetChild(0).interpretToLambda(problems,expression,functionClassifier,mapResolver);
		checkOrAdd("Or expression failed, first expression is not a boolean but a "+expA.returnType().map(ImmutableTypeParser::typeName).orElse("<unknown>"), problems, expA.returnType(), ValueType.BOOLEAN);
		ContextExpression expB = jjtGetChild(1).interpretToLambda(problems,expression,functionClassifier,mapResolver);
		checkOrAdd("Or expression failed, second expression is not a boolean but a "+expB.returnType().map(ImmutableTypeParser::typeName).orElse("<unknown>"), problems, expB.returnType(), ValueType.BOOLEAN);
		return new ContextExpression() {
			
			@Override
			public boolean isLiteral() {
				return expA.isLiteral() && expB.isLiteral();
			}
			
			@Override
			public Operand apply(Optional<ImmutableMessage> immutableMessage, Optional<ImmutableMessage> paramMessage) {
		        Object a = expA.apply(immutableMessage,paramMessage).value;
		        Boolean ba = (Boolean) a;
		        if(a==null) {
		        		ba = Boolean.FALSE;
		        }
		        if (ba.booleanValue())
		            return Operand.ofBoolean(true);

		        Object b = expB.apply(immutableMessage,paramMessage).value;
		        Boolean bb = (Boolean) b;
		        if(b==null) {
		        		bb = Boolean.FALSE;
		        }

		        return Operand.ofBoolean(ba.booleanValue() || bb.booleanValue());
			}

			@Override
			public Optional<ValueType> returnType() {
				return Optional.of(ValueType.BOOLEAN);
			}
			
			@Override
			public String expression() {
				return expression;
			}
		};
    }
}
