/* Generated By:JJTree&JavaCC: Do not edit this line. ASTTodayNode.java */
package com.dexels.navajo.parser.compiled;


import com.dexels.immutable.api.ImmutableMessage;
import com.dexels.navajo.document.*;
import com.dexels.navajo.expression.api.ContextExpression;
import com.dexels.navajo.expression.api.FunctionClassification;
import com.dexels.navajo.expression.api.TipiLink;
import com.dexels.navajo.script.api.Access;
import com.dexels.navajo.script.api.MappableTreeNode;

import java.util.Date;
import java.util.List;
import java.util.Optional;
import java.util.function.Function;


final class ASTTodayNode extends SimpleNode {
    ASTTodayNode(int id) {
        super(id);
    }

	@Override
	public ContextExpression interpretToLambda(List<String> problems, String expression, Function<String, FunctionClassification> functionClassifier, Function<String,Optional<Node>> mapResolver) {
		return new ContextExpression() {

			@Override
			public Operand apply(MappableTreeNode mapNode,Optional<ImmutableMessage> immutableMessage, Optional<ImmutableMessage> paramMessage) {
				return Operand.ofDate(new Date());
			}

			@Override
			public boolean isLiteral() {
				return false;
			}

			@Override
			public Optional<String> returnType() {
				return Optional.of(Property.DATE_PROPERTY);
			}
			
			@Override
			public String expression() {
				return expression;
			}
		};
	}
}
