/* Generated By:JavaCC: Do not edit this line. CompiledParserTreeConstants.java Version 4.2 */
package com.dexels.navajo.parser.compiled;

public interface CompiledParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTLISTNODE = 1;
  public int JJTPIPEDEFINITION = 2;
  public int JJTREACTIVESCRIPTNODE = 3;
  public int JJTORNODE = 4;
  public int JJTANDNODE = 5;
  public int JJTEQNODE = 6;
  public int JJTNENODE = 7;
  public int JJTLTNODE = 8;
  public int JJTGTNODE = 9;
  public int JJTLENODE = 10;
  public int JJTGENODE = 11;
  public int JJTADDNODE = 12;
  public int JJTSUBTRACTNODE = 13;
  public int JJTMULNODE = 14;
  public int JJTDIVNODE = 15;
  public int JJTMODNODE = 16;
  public int JJTNEGATIVENODE = 17;
  public int JJTNOTNODE = 18;
  public int JJTNULLNODE = 19;
  public int JJTTODAYNODE = 20;
  public int JJTTRUENODE = 21;
  public int JJTFALSENODE = 22;
  public int JJTFORALLNODE = 23;
  public int JJTFUNCTIONNODE = 24;
  public int JJTFLOATCONSTANTNODE = 25;
  public int JJTINTEGERCONSTANTNODE = 26;
  public int JJTSTRINGCONSTANTNODE = 27;
  public int JJTEXPRESSIONLITERALNODE = 28;
  public int JJTTMLNODE = 29;
  public int JJTTIPINODE = 30;
  public int JJTMAPPABLENODE = 31;
  public int JJTKEYVALUENODE = 32;


  public String[] jjtNodeName = {
    "void",
    "ListNode",
    "PipeDefinition",
    "ReactiveScriptNode",
    "OrNode",
    "AndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "NegativeNode",
    "NotNode",
    "NullNode",
    "TodayNode",
    "TrueNode",
    "FalseNode",
    "ForAllNode",
    "FunctionNode",
    "FloatConstantNode",
    "IntegerConstantNode",
    "StringConstantNode",
    "ExpressionLiteralNode",
    "TmlNode",
    "TipiNode",
    "MappableNode",
    "KeyValueNode",
  };
}
/* JavaCC - OriginalChecksum=30168b309e1b8f4c5b8c779e7de71a8c (do not edit this line) */
