/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.floodplain.kotlindsl

import com.dexels.immutable.api.ImmutableMessage
import com.dexels.immutable.factory.ImmutableFactory
import io.floodplain.kotlindsl.message.IMessage
import io.floodplain.kotlindsl.message.fromImmutable
import kotlin.test.Test

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val m = ImmutableFactory.empty().with("aap", "vla", ImmutableMessage.ValueType.STRING)
        val msg: IMessage = fromImmutable(m)
        val m2 = msg.toImmutable()
        println("Aap: ${m2.value("aap")}")
//        val classUnderTest = App()
        //      assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
