/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.floodplain.kotlindsl

import io.floodplain.immutable.api.ImmutableMessage
import io.floodplain.immutable.factory.ImmutableFactory
import io.floodplain.kotlindsl.message.IMessage
import io.floodplain.kotlindsl.message.fromImmutable
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class IMessageTest {
    @Test
    fun testAppHasAGreeting() {
        val m = ImmutableFactory.empty().with("aap", "vla", ImmutableMessage.ValueType.STRING)
        val msg: IMessage = fromImmutable(m)!!
        val m2 = msg.toImmutable()
        assertNotNull(m2.value("aap"), "app conversion has failed")
        assertEquals("vla", m2.value("aap").get() as String)
    }
}
