CREATE CONSTRAINT ON (n:Club) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Person) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Team) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Match) ASSERT n.id IS UNIQUE;
//CREATE INDEX ON :Club(id)
//CREATE INDEX ON :Person(id)
//CREATE INDEX ON :Team(id)
//CREATE INDEX ON :Match(id)
